kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "pyazo.fullname" . }}-data
  labels:
    type: local
    app.kubernetes.io/name: {{ include "pyazo.name" . }}
    helm.sh/chart: {{ include "pyazo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pyazo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: {{ include "pyazo.name" . }}
    helm.sh/chart: {{ include "pyazo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "pyazo.fullname" . }}-data
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
